### ISSUE TITLE
Error in inject_fooocus_inpaint_head during training

### ISSUE THREAD

**Issue by chuntingye** [mycfhs/DreamMix#5]
Thanks for your amazing work!
I encounter errors when I try to train lora on my custom objects. I've prepared the datasets (with make_imgs.ipynb) and downloaded required models as you mentioned. The command used for training is:

```
CATEGORY="shoes"  
INSTANCE_PROMPT="A sks black safety shoes"  
accelerate launch train.py \
    --category="${CATEGORY}" \
    --output_dir="lora/${CATEGORY}" \
    --regular_dir="./regular_${CATEGORY}" \
    --regular_prob=0.3 \
    --loss_reweight_object=1.5 \
    --loss_reweight_background=0.6 \
    --pretrained_model_name_or_path="frankjoshua/juggernautXL_v8Rundiffusion" \
    --instance_data_dir="train_data/dataset/${CATEGORY}/image" \
    --mixed_precision="no" \
    --instance_prompt="${INSTANCE_PROMPT}" \
    --resolution=1024 \
    --train_batch_size=1 \
    --gradient_accumulation_steps=4 \
    --learning_rate=1e-4 \
    --lr_scheduler="constant" \
    --lr_warmup_steps=0 \
    --max_train_steps=1000 \
    --seed="0" \
    --checkpointing_steps=250 \
    --resume_from_checkpoint="latest" \
    --enable_xformers_memory_efficient_attention
```

and the errors occur after the training script encodes the latent and start to train. It seems that there are missing attributes in function `inject_fooocus_inpaint_head` and I'm not sure if this function belongs to the method of `InpaintHead` originally. The following is a part of error messages:

```
12/17/2024 09:43:48 - INFO - __main__ - ***** Running training *****                                                                                                                                        
12/17/2024 09:43:48 - INFO - __main__ -   Num examples = 500                                                                                                                                                
12/17/2024 09:43:48 - INFO - __main__ -   Num batches each epoch = 500                                                                                                                                      
12/17/2024 09:43:48 - INFO - __main__ -   Num Epochs = 8                                                                                                                                                    
12/17/2024 09:43:48 - INFO - __main__ -   Instantaneous batch size per device = 1                                                                                                                           
12/17/2024 09:43:48 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 4                                                                                              
12/17/2024 09:43:48 - INFO - __main__ -   Gradient Accumulation steps = 4                                                                                                                                   
12/17/2024 09:43:48 - INFO - __main__ -   Total optimization steps = 1000                                                                                                                                   
Checkpoint 'latest' does not exist. Starting a new training run.                                                                                                                                            
Steps:   0%|                                                                                                                                                                              | 0/1000 [00:00<?,
 ?it/s]Traceback (most recent call last):                                                                                                                                                                   
  File "/home/yct/projects/DreamMix/train.py", line 2171, in <module>                                                                                                                                       
    main(args)                                                                                                                                                                                              
  File "/home/yct/projects/DreamMix/train.py", line 1938, in main                                                                                                                                           
    model_pred = unet(                                                                                                                                                                                      
  File "/home/yct/.pyenv/versions/3.10.15/envs/DreamMix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl                                                          
    return self._call_impl(*args, **kwargs)                                                                                                                                                                 
  File "/home/yct/.pyenv/versions/3.10.15/envs/DreamMix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl                                                                  
    return forward_call(*args, **kwargs)                                                                                                                                                                    
  File "/home/yct/projects/DreamMix/utils/add_fooocus_inpaint_head_patch.py", line 137, in forward                                                                                                          
    if self.config.center_input_sample:                                                                                                                                                                     
AttributeError: 'function' object has no attribute 'config'                                                                                                                                                 
Steps:   0%|
```

**Comment by mycfhs** [comment]
Try setting parallel_train=False in train.py at line 1834.

**Comment by chuntingye** [comment]
It fixes the error and the root cause is I trained the model on single RTX3090 which is not assumed by the training script. I'll go ahead and close the issue. Thank you.

**Comment by chuntingye** [comment]
It fixes the error and the root cause is I trained the model on single RTX3090 which is not assumed by the training script. I'll go ahead and close the issue. Thank you.
